### ISSUE TITLE
HREDBADMIN gets a null pointer exception when run as stand-alone application

### ISSUE THREAD

**Issue by MichaelErichsen** [History-Research-Environment/HRE--History-Research-Environment#11]

**Comment by MichaelErichsen** [comment]
When starting from scratch gets an org.h2.jdbc.JdbcSQLException: Database "C:/Temp/HRE010" not found [90013-168]

**Comment by MichaelErichsen** [comment]
Opening a projects gets an Internal error, Reason: org.eclipse.e4.core.InjectionException: java.lang.NullPointerException

**Comment by MichaelErichsen** [comment]
Creating a new projects gets 
org.h2.jdbc.JdbcSQLException: Column "ROW_COUNT_ESTIMATE" not found; SQL statement:
SELECT TABLE_NAME, ROW_COUNT_ESTIMATE FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'TABLE' ORDER BY TABLE_NAME [42122-168]
The database has been created, and the statement executes successfully when run interactively and from inside the Eclipse Workbench

**Comment by MichaelErichsen** [comment]
Logger added

**Comment by MichaelErichsen** [comment]
org.eclipse.e4.core.di.InjectionException: java.lang.NullPointerException
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:65)
...
Caused by: java.lang.NullPointerException
	at org.historyresearchenvironment.databaseadmin.providers.H2DatabaseProvider.<init>(H2DatabaseProvider.java:39)
	at org.historyresearchenvironment.databaseadmin.parts.H2DatabaseNavigator.updateGui(H2DatabaseNavigator.java:151)
	at org.historyresearchenvironment.databaseadmin.parts.H2DatabaseNavigator.subscribeDatabaseNameUpdateTopic(H2DatabaseNavigator.java:136)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
	... 22 more

				final PreparedStatement ps = conn.prepareStatement(SELECT);

**Comment by MichaelErichsen** [comment]
From Eclipse:

org.historyresearchenvironment.databaseadmin.providers.H2DatabaseProvider <init>
INFO: Database name: C:\Users\michael/HRE
May 21, 2018 11:47:52 AM 

Stand-alone:

org.historyresearchenvironment.databaseadmin.HreH2ConnectionPool getConnection
SEVERE: Database "C:/Users/michael/HRE" not found [90013-168]

**Comment by MichaelErichsen** [comment]
org.historyresearchenvironment.databaseadmin.HreH2ConnectionPool getConnection
INFO: JDBC URL: jdbc:h2:C:\Users\michael/HRE;IFEXISTS=TRUE;TRACE_LEVEL_FILE=2;TRACE_LEVEL_SYSTEM_OUT=2
May 21, 2018 11:47:52 AM 

maj 21, 2018 11:55:24 AM org.historyresearchenvironment.databaseadmin.HreH2ConnectionPool getConnection
INFO: JDBC URL: jdbc:h2:~/HRE;IFEXISTS=TRUE;TRACE_LEVEL_FILE=2;TRACE_LEVEL_SYSTEM_OUT=2

**Comment by MichaelErichsen** [comment]
Reason seems to be a mismatch between H2 versions (168 and 197)

**Comment by MichaelErichsen** [comment]
Maven/Tycho build decides to fetch an old version of h2:
Fetching org.h2_1.3.168.v201212121212.jar from http://ftp.fau.de/eclipse/releases/oxygen/201804111000/plugins/

**Comment by MichaelErichsen** [comment]
Column "ROW_COUNT_ESTIMATE" does not exist in H2 version 1.3.

**Comment by MichaelErichsen** [comment]
Column removed from database navigator
